# Generated by Django 4.1.3 on 2022-12-01 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_alter_user_intake_alter_user_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_edit_levels', models.BooleanField(default=False, null=True)),
                ('see_intake_level_statistics', models.BooleanField(default=False, null=True)),
                ('can_edit_users_data', models.BooleanField(default=False, null=True)),
                ('can_edit_exam_results', models.BooleanField(default=False, null=True)),
                ('supervisor', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
