# Generated by Django 4.1.3 on 2022-12-01 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_alter_user_courses_alter_user_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissions',
            name='can_edit_exams',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
