# Generated by Django 4.1.3 on 2022-12-02 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Levels', '0002_subject_tutor_name'),
        ('Users', '0007_permissions_can_edit_exams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intake',
            name='level',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Levels.level'),
        ),
    ]
