# Generated by Django 4.1.3 on 2022-12-08 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0010_rename_can_edit_exams_permissions_can_edit_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissions',
            name='can_edit_level',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='permissions',
            name='can_edit_subject',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
