# Generated by Django 4.2.2 on 2023-06-20 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Intakes', '0001_initial'),
        ('Users', '0011_permissions_can_edit_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='intake',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Intakes.intake'),
        ),
        migrations.DeleteModel(
            name='Intake',
        ),
    ]
