# Generated by Django 4.2.2 on 2023-06-25 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0012_alter_user_intake_delete_intake'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permissions',
            name='can_edit_level',
        ),
        migrations.AddField(
            model_name='permissions',
            name='can_edit_intakes',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='permissions',
            name='can_edit_exam',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='permissions',
            name='can_edit_exam_results',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='permissions',
            name='can_edit_levels',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='permissions',
            name='can_edit_subject',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='permissions',
            name='can_edit_users_data',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='permissions',
            name='see_intake_level_statistics',
            field=models.BooleanField(null=True),
        ),
    ]
