# Generated by Django 4.2.2 on 2023-07-03 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0013_remove_permissions_can_edit_level_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permissions',
            old_name='see_intake_level_statistics',
            new_name='can_edit_landing_page',
        ),
        migrations.AddField(
            model_name='permissions',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='permissions',
            name='see_statistics',
            field=models.BooleanField(null=True),
        ),
    ]
