# Generated by Django 4.2.2 on 2023-06-20 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Levels', '0003_lesson_lesson_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('intake_description', models.TextField()),
                ('start_date', models.DateField(auto_now=True)),
                ('register_date', models.DateField()),
                ('expire_date', models.DateField()),
                ('telegram_link_men', models.URLField()),
                ('telegram_link_women', models.URLField()),
                ('level', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Levels.level')),
            ],
        ),
    ]
