# Generated by Django 4.1.2 on 2022-12-19 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exams', '0003_options_correct_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='exam',
        ),
        migrations.AddField(
            model_name='options',
            name='final_mark',
            field=models.IntegerField(default=False, null=True),
        ),
    ]
