# Generated by Django 4.1.2 on 2023-05-03 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exams', '0004_remove_answers_exam_options_final_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='comment',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='end_date',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='exam',
            name='start_date',
            field=models.DateTimeField(default=None),
        ),
    ]
