# Generated by Django 4.2.1 on 2023-05-12 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Exams', '0005_alter_exam_comment_alter_exam_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='answer',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Exams.options'),
        ),
    ]
