# Generated by Django 4.2.1 on 2023-06-18 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exams', '0007_answers_exam_alter_marks_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='mark',
            field=models.IntegerField(default=0),
        ),
    ]
