# Generated by Django 4.2.2 on 2023-06-20 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Subjects', '0001_initial'),
        ('Exams', '0008_alter_marks_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='subj',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Subjects.subject'),
        ),
    ]
