# Generated by Django 4.2.2 on 2023-06-26 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Subjects', '0002_remove_subject_exams'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='tutor_name',
        ),
    ]
