# Generated by Django 4.2.2 on 2023-06-26 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Subjects', '0003_remove_subject_tutor_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='subject_name',
            new_name='name',
        ),
    ]
