# Generated by Django 4.2.2 on 2023-06-27 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Subjects', '0004_rename_subject_name_subject_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='lesson_name',
            new_name='name',
        ),
    ]
