# Generated by Django 4.2.2 on 2023-07-01 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Subjects', '0005_rename_lesson_name_lesson_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='subject_level',
            new_name='level',
        ),
    ]
