# Generated by Django 4.1.2 on 2022-11-28 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Exams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_name', models.CharField(max_length=100)),
                ('number_of_students', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('level_statues', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100)),
                ('exams', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Exams.exam')),
                ('subject_level', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Levels.level')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_description', models.TextField()),
                ('lesson_pdf', models.URLField()),
                ('lesson_video', models.URLField()),
                ('subject', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Levels.subject')),
            ],
        ),
    ]
