# Generated by Django 4.1.3 on 2022-12-08 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Levels', '0002_subject_tutor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lesson_name',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
