# Generated by Django 4.2.2 on 2023-06-20 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Levels', '0003_lesson_lesson_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='exams',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='subject_level',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='tutor_name',
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
    ]
