# Generated by Django 4.2.2 on 2023-06-20 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Exams', '0009_alter_exam_subj'),
        ('Levels', '0004_remove_subject_exams_remove_subject_subject_level_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
